export const stages = [
  { id: 'lead', label: 'سرنخ', color: '#6366f1', count: 3 },
  { id: 'qualified', label: 'تایید شده', color: '#3b82f6', count: 2 },
  { id: 'discovery', label: 'کشف نیاز', color: '#06b6d4', count: 2 },
  { id: 'proposal', label: 'پیشنهاد', color: '#f59e0b', count: 2 },
  { id: 'negotiation', label: 'مذاکره', color: '#f97316', count: 2 },
  { id: 'won', label: 'برنده', color: '#22c55e', count: 1 },
];

export const deals = [
  {
    id: 1,
    title: 'قرارداد CRM شرکت آلفا',
    company: 'شرکت آلفا',
    contact: 'علی محمدی',
    value: 450000000,
    stage: 'negotiation',
    health: 78,
    probability: 70,
    daysInStage: 5,
    lastActivity: '۲ روز پیش',
    lastActivityType: 'تماس تلفنی',
    nextAction: 'ارسال پیشنهاد نهایی',
    createdAt: '۱۴۰۵/۰۶/۰۱',
    owner: 'علی رضایی',
    tags: ['بزرگ', 'SaaS', 'تهران'],
  },
  {
    id: 2,
    title: 'پروژه دیجیتال مارکتینگ بتا',
    company: 'شرکت بتا',
    contact: 'سارا احمدی',
    value: 180000000,
    stage: 'proposal',
    health: 45,
    probability: 50,
    daysInStage: 12,
    lastActivity: '۸ روز پیش',
    lastActivityType: 'ایمیل',
    nextAction: 'پیگیری پیشنهاد ارسال شده',
    createdAt: '۱۴۰۵/۰۵/۲۰',
    owner: 'علی رضایی',
    tags: ['متوسط', 'مارکتینگ'],
  },
  {
    id: 3,
    title: 'فروش لایسنس نرم‌افزار گاما',
    company: 'شرکت گاما',
    contact: 'رضا کریمی',
    value: 320000000,
    stage: 'discovery',
    health: 82,
    probability: 40,
    daysInStage: 3,
    lastActivity: 'دیروز',
    lastActivityType: 'جلسه آنلاین',
    nextAction: 'ارسال سوالات کشف نیاز',
    createdAt: '۱۴۰۵/۰۶/۱۰',
    owner: 'مریم نوری',
    tags: ['بزرگ', 'نرم‌افزار'],
  },
  {
    id: 4,
    title: 'مشاوره ERP شرکت دلتا',
    company: 'شرکت دلتا',
    contact: 'مهدی حسینی',
    value: 95000000,
    stage: 'qualified',
    health: 60,
    probability: 30,
    daysInStage: 7,
    lastActivity: '۵ روز پیش',
    lastActivityType: 'فرم وب',
    nextAction: 'تماس برای جلسه معرفی',
    createdAt: '۱۴۰۵/۰۶/۰۵',
    owner: 'علی رضایی',
    tags: ['کوچک', 'ERP'],
  },
  {
    id: 5,
    title: 'قرارداد پشتیبانی شرکت اپسیلون',
    company: 'شرکت اپسیلون',
    contact: 'نیلوفر شریفی',
    value: 670000000,
    stage: 'negotiation',
    health: 35,
    probability: 60,
    daysInStage: 18,
    lastActivity: '۱۲ روز پیش',
    lastActivityType: 'ایمیل',
    nextAction: 'تماس فوری - معامله در خطر',
    createdAt: '۱۴۰۵/۰۴/۱۵',
    owner: 'مریم نوری',
    tags: ['بزرگ', 'پشتیبانی', 'در خطر'],
  },
  {
    id: 6,
    title: 'سیستم حسابداری شرکت زتا',
    company: 'شرکت زتا',
    contact: 'حسن عباسی',
    value: 150000000,
    stage: 'lead',
    health: 90,
    probability: 10,
    daysInStage: 1,
    lastActivity: 'امروز',
    lastActivityType: 'فرم وب',
    nextAction: 'بررسی صلاحیت سرنخ',
    createdAt: '۱۴۰۵/۰۶/۱۹',
    owner: 'علی رضایی',
    tags: ['کوچک', 'حسابداری'],
  },
  {
    id: 7,
    title: 'پلتفرم آموزش آنلاین اتا',
    company: 'شرکت اتا',
    contact: 'زهرا کاظمی',
    value: 280000000,
    stage: 'proposal',
    health: 72,
    probability: 55,
    daysInStage: 6,
    lastActivity: '۳ روز پیش',
    lastActivityType: 'جلسه حضوری',
    nextAction: 'ارسال نمونه پروژه قبلی',
    createdAt: '۱۴۰۵/۰۵/۲۸',
    owner: 'مریم نوری',
    tags: ['متوسط', 'آموزش'],
  },
  {
    id: 8,
    title: 'اتوماسیون بازاریابی شرکت تتا',
    company: 'شرکت تتا',
    contact: 'امیر رستمی',
    value: 520000000,
    stage: 'discovery',
    health: 88,
    probability: 35,
    daysInStage: 2,
    lastActivity: 'دیروز',
    lastActivityType: 'تلفن',
    nextAction: 'برنامه‌ریزی جلسه دوم',
    createdAt: '۱۴۰۵/۰۶/۱۲',
    owner: 'علی رضایی',
    tags: ['بزرگ', 'اتوماسیون'],
  },
  {
    id: 9,
    title: 'فروش سخت‌افزار شرکت یوتا',
    company: 'شرکت یوتا',
    contact: 'پریسا مهدوی',
    value: 85000000,
    stage: 'lead',
    health: 95,
    probability: 5,
    daysInStage: 0,
    lastActivity: 'امروز',
    lastActivityType: 'لینکدین',
    nextAction: 'ارسال پیام معرفی',
    createdAt: '۱۴۰۵/۰۶/۱۹',
    owner: 'مریم نوری',
    tags: ['کوچک', 'سخت‌افزار'],
  },
  {
    id: 10,
    title: 'قرارداد سالانه شرکت فی',
    company: 'شرکت فی',
    contact: 'محمدرضا سلیمانی',
    value: 890000000,
    stage: 'won',
    health: 100,
    probability: 100,
    daysInStage: 0,
    lastActivity: '۱ روز پیش',
    lastActivityType: 'امضای قرارداد',
    nextAction: 'شروع پروژه آنبوردینگ',
    createdAt: '۱۴۰۵/۰۳/۰۱',
    owner: 'علی رضایی',
    tags: ['بزرگ', 'سالانه', 'برنده شده'],
  },
  {
    id: 11,
    title: 'مشاوره دیجیتال شرکت کاپا',
    company: 'شرکت کاپا',
    contact: 'الهام جعفری',
    value: 120000000,
    stage: 'lead',
    health: 85,
    probability: 8,
    daysInStage: 2,
    lastActivity: '۲ روز پیش',
    lastActivityType: 'فرم وب',
    nextAction: 'بررسی و تایید صلاحیت',
    createdAt: '۱۴۰۵/۰۶/۱۷',
    owner: 'مریم نوری',
    tags: ['متوسط', 'مشاوره'],
  },
  {
    id: 12,
    title: 'سیستم مدیریت محتوا شرکت لاندا',
    company: 'شرکت لاندا',
    contact: 'بهنام امیری',
    value: 230000000,
    stage: 'qualified',
    health: 55,
    probability: 25,
    daysInStage: 9,
    lastActivity: '۷ روز پیش',
    lastActivityType: 'ایمیل',
    nextAction: 'ارسال دعوتنامه جلسه',
    createdAt: '۱۴۰۵/۰۵/۳۰',
    owner: 'علی رضایی',
    tags: ['متوسط', 'CMS'],
  },
];

export const contacts = [
  { id: 1, name: 'علی محمدی', company: 'شرکت آلفا', phone: '۰۹۱۲۱۲۳۴۵۶۷', email: 'ali@alpha.com', role: 'مدیر فروش', lastContact: '۲ روز پیش', dealCount: 1, avatar: 'ع' },
  { id: 2, name: 'سارا احمدی', company: 'شرکت بتا', phone: '۰۹۱۹۸۷۶۵۴۳۲', email: 'sara@beta.com', role: 'مدیر پروژه', lastContact: '۸ روز پیش', dealCount: 1, avatar: 'س' },
  { id: 3, name: 'رضا کریمی', company: 'شرکت گاما', phone: '۰۹۱۱۱۱۱۱۱۱۱', email: 'reza@gamma.com', role: 'مدیر عامل', lastContact: 'دیروز', dealCount: 1, avatar: 'ر' },
  { id: 4, name: 'مهدی حسینی', company: 'شرکت دلتا', phone: '۰۹۱۲۲۲۲۲۲۲۲', email: 'mehdi@delta.com', role: 'مدیر IT', lastContact: '۵ روز پیش', dealCount: 1, avatar: 'م' },
  { id: 5, name: 'نیلوفر شریفی', company: 'شرکت اپسیلون', phone: '۰۹۱۹۳۳۳۳۳۳۳', email: 'niloufar@epsilon.com', role: 'مدیر خرید', lastContact: '۱۲ روز پیش', dealCount: 1, avatar: 'ن' },
  { id: 6, name: 'حسن عباسی', company: 'شرکت زتا', phone: '۰۹۱۲۴۴۴۴۴۴۴۴', email: 'hasan@zeta.com', role: 'حسابدار', lastContact: 'امروز', dealCount: 1, avatar: 'ح' },
  { id: 7, name: 'زهرا کاظمی', company: 'شرکت اتا', phone: '۰۹۱۹۵۵۵۵۵۵۵', email: 'zahra@eta.com', role: 'مدیر آموزش', lastContact: '۳ روز پیش', dealCount: 1, avatar: 'ز' },
  { id: 8, name: 'امیر رستمی', company: 'شرکت تتا', phone: '۰۹۱۲۶۶۶۶۶۶۶', email: 'amir@theta.com', role: 'مدیر بازاریابی', lastContact: 'دیروز', dealCount: 1, avatar: 'ا' },
];

export const activities = [
  { id: 1, dealId: 1, type: 'call', title: 'تماس تلفنی', description: 'پیگیری شرایط قرارداد و بحث درباره قیمت', date: '۱۴۰۵/۰۶/۱۷', time: '۱۴:۳۰', icon: '📞' },
  { id: 2, dealId: 1, type: 'meeting', title: 'جلسه آنلاین', description: 'ارائه نهایی پیشنهاد به تیم خرید آلفا', date: '۱۴۰۵/۰۶/۱۵', time: '۱۰:۰۰', icon: '📹' },
  { id: 3, dealId: 1, type: 'email', title: 'ایمیل', description: 'ارسال شرایط تفصیلی قرارداد', date: '۱۴۰۵/۰۶/۱۴', time: '۱۱:۲۰', icon: '📧' },
  { id: 4, dealId: 1, type: 'task', title: 'تسک', description: 'تهیه پروپوزال نهایی', date: '۱۴۰۵/۰۶/۱۲', time: '۰۹:۰۰', icon: '✅' },
  { id: 5, dealId: 5, type: 'call', title: 'تماس تلفنی', description: 'بازخورد منفی درباره قیمت - نیاز به تخفیف', date: '۱۴۰۵/۰۶/۰۷', time: '۱۶:۰۰', icon: '📞' },
  { id: 6, dealId: 5, type: 'email', title: 'ایمیل', description: 'ارسال فاکتور اصلاح شده', date: '۱۴۰۵/۰۶/۰۵', time: '۱۰:۳۰', icon: '📧' },
  { id: 7, dealId: 5, type: 'meeting', title: 'جلسه حضوری', description: 'مذاکره حضوری در دفتر شرکت اپسیلون', date: '۱۴۰۵/۰۶/۰۱', time: '۱۴:۰۰', icon: '🤝' },
  { id: 8, dealId: 10, type: 'task', title: 'تسک', description: 'امضای نهایی قرارداد و شروع آنبوردینگ', date: '۱۴۰۵/۰۶/۱۸', time: '۱۱:۰۰', icon: '✅' },
  { id: 9, dealId: 3, type: 'meeting', title: 'جلسه آنلاین', description: 'کشف نیازهای اصلی شرکت گاما', date: '۱۴۰۵/۰۶/۱۸', time: '۰۹:۳۰', icon: '📹' },
  { id: 10, dealId: 8, type: 'call', title: 'تماس تلفنی', description: 'معرفی اولیه پلتفرم اتوماسیون', date: '۱۴۰۵/۰۶/۱۸', time: '۱۵:۰۰', icon: '📞' },
];

export const aiInsights = [
  { id: 1, type: 'danger', title: 'معامله در خطر', message: 'قرارداد پشتیبانی اپسیلون ۱۸ روز بدون فعالیت است. احتمال از دست رفتن: ۶۵٪', action: 'تماس فوری', dealId: 5 },
  { id: 2, type: 'warning', title: 'پیگیری عقب‌افتاده', message: 'پیشنهاد شرکت بتا ۱۲ روز ارسال شده و پاسخی دریافت نشده', action: 'ارسال یادآوری', dealId: 2 },
  { id: 3, type: 'success', title: 'معامله با احتمال بالا', message: 'قرارداد آلفا در مرحله مذاکره با احتمال ۷۰٪ — آماده بستن', action: 'پیگیری نهایی', dealId: 1 },
  { id: 4, type: 'info', title: 'پیشنهاد هوشمند', message: 'بر اساس الگوهای تاریخی، معاملات مشابه با شرکت‌های بزرگ بعد از ۳ جلسه بسته می‌شوند', action: 'مشاهده', dealId: 3 },
  { id: 5, type: 'info', title: 'تحلیل فصلی', message: 'نرخ تبدیل فروش در این فصل نسبت به فصل قبل ۱۵٪ بهبود داشته', action: 'مشاهده گزارش', dealId: null },
];

// ─── Case Workflows ───────────────────────────────────────────────────────

export const followUpStages = [
  { id: 'new', label: 'جدید', color: '#6366f1', icon: '🆕' },
  { id: 'initial_call', label: 'تماس اولیه', color: '#3b82f6', icon: '📞' },
  { id: 'followup_1', label: 'پیگیری اول', color: '#06b6d4', icon: '🔄' },
  { id: 'followup_2', label: 'پیگیری دوم', color: '#f59e0b', icon: '🔄' },
  { id: 'followup_3', label: 'پیگیری سوم', color: '#f97316', icon: '⚠️' },
  { id: 'successful', label: 'موفق', color: '#22c55e', icon: '✅' },
  { id: 'closed', label: 'بسته شده', color: '#ef4444', icon: '🔒' },
];

export const contractStages = [
  { id: 'drafting', label: 'در حال تنظیم', color: '#6366f1', icon: '📝' },
  { id: 'legal_review', label: 'بررسی حقوقی', color: '#3b82f6', icon: '⚖️' },
  { id: 'awaiting_signature', label: 'در انتظار امضا', color: '#f59e0b', icon: '✍️' },
  { id: 'active', label: 'فعال', color: '#22c55e', icon: '🟢' },
  { id: 'renewal', label: 'نیاز به تمدید', color: '#f97316', icon: '🔄' },
  { id: 'expired', label: 'منقضی شده', color: '#ef4444', icon: '🔴' },
];

export const followUpCases = [
  {
    id: 101,
    title: 'پیگیری فروش سیستم CRM',
    company: 'شرکت آلفا',
    contact: 'علی محمدی',
    stage: 'followup_2',
    priority: 'high',
    dueDate: '۱۴۰۵/۰۶/۲۳',
    lastContact: '۳ روز پیش',
    contactMethod: 'تماس تلفنی',
    notes: 'مشتری علاقه‌مند اما نیاز به تخفیف دارد',
    attemptCount: 2,
    owner: 'علی رضایی',
    dealId: 1,
  },
  {
    id: 102,
    title: 'پیگیری ارسال پیشنهاد',
    company: 'شرکت بتا',
    contact: 'سارا احمدی',
    stage: 'followup_1',
    priority: 'medium',
    dueDate: '۱۴۰۵/۰۶/۲۵',
    lastContact: '۵ روز پیش',
    contactMethod: 'ایمیل',
    notes: 'پیشنهاد ارسال شده، پاسخی دریافت نشده',
    attemptCount: 1,
    owner: 'علی رضایی',
    dealId: 2,
  },
  {
    id: 103,
    title: 'پیگیری جلسه معرفی',
    company: 'شرکت گاما',
    contact: 'رضا کریمی',
    stage: 'new',
    priority: 'high',
    dueDate: '۱۴۰۵/۰۶/۲۲',
    lastContact: '—',
    contactMethod: '—',
    notes: 'سرنخ جدید از وبینار، نیاز به تماس اولیه',
    attemptCount: 0,
    owner: 'مریم نوری',
    dealId: 3,
  },
  {
    id: 104,
    title: 'پیگیری بعد از دمو',
    company: 'شرکت دلتا',
    contact: 'مهدی حسینی',
    stage: 'initial_call',
    priority: 'low',
    dueDate: '۱۴۰۵/۰۶/۲۸',
    lastContact: '۱ روز پیش',
    contactMethod: 'جلسه آنلاین',
    notes: 'دمو انجام شده، منتظر بازخورد',
    attemptCount: 1,
    owner: 'علی رضایی',
    dealId: 4,
  },
  {
    id: 105,
    title: 'پیگیری قرارداد پشتیبانی',
    company: 'شرکت اپسیلون',
    contact: 'نیلوفر شریفی',
    stage: 'followup_3',
    priority: 'high',
    dueDate: '۱۴۰۵/۰۶/۲۱',
    lastContact: '۱۲ روز پیش',
    contactMethod: 'ایمیل',
    notes: '⚠️ خطر از دست دادن مشتری — تخفیف پیشنهادی رد شد',
    attemptCount: 3,
    owner: 'مریم نوری',
    dealId: 5,
  },
  {
    id: 106,
    title: 'پیگیری فاکتور شرکت فی',
    company: 'شرکت فی',
    contact: 'محمدرضا سلیمانی',
    stage: 'successful',
    priority: 'low',
    dueDate: '۱۴۰۵/۰۶/۱۹',
    lastContact: 'امروز',
    contactMethod: 'امضای قرارداد',
    notes: 'قرارداد امضا شد ✓',
    attemptCount: 2,
    owner: 'علی رضایی',
    dealId: 10,
  },
  {
    id: 107,
    title: 'پیگیری مشاوره دیجیتال',
    company: 'شرکت کاپا',
    contact: 'الهام جعفری',
    stage: 'new',
    priority: 'medium',
    dueDate: '۱۴۰۵/۰۶/۲۴',
    lastContact: '—',
    contactMethod: '—',
    notes: 'فرم وب تکمیل شده — نیاز به تماس',
    attemptCount: 0,
    owner: 'مریم نوری',
    dealId: 11,
  },
  {
    id: 108,
    title: 'پیگیری CMS شرکت لاندا',
    company: 'شرکت لاندا',
    contact: 'بهنام امیری',
    stage: 'closed',
    priority: 'low',
    dueDate: '۱۴۰۵/۰۶/۱۰',
    lastContact: '۱۰ روز پیش',
    contactMethod: 'ایمیل',
    notes: 'مشتری پاسخ نداد — بسته شد',
    attemptCount: 3,
    owner: 'علی رضایی',
    dealId: 12,
  },
];

export const contractCases = [
  {
    id: 201,
    title: 'قرارداد سالانه شرکت آلفا',
    company: 'شرکت آلفا',
    contact: 'علی محمدی',
    stage: 'awaiting_signature',
    value: 450000000,
    startDate: '۱۴۰۵/۰۷/۰۱',
    endDate: '۱۴۰۶/۰۶/۳۰',
    daysRemaining: 40,
    lastActivity: '۲ روز پیش',
    status: 'waiting',
    owner: 'علی رضایی',
    dealId: 1,
  },
  {
    id: 202,
    title: 'قرارداد پشتیبانی اپسیلون',
    company: 'شرکت اپسیلون',
    contact: 'نیلوفر شریفی',
    stage: 'active',
    value: 670000000,
    startDate: '۱۴۰۵/۰۱/۰۱',
    endDate: '۱۴۰۵/۱۲/۲۹',
    daysRemaining: 120,
    lastActivity: '۱۲ روز پیش',
    status: 'at_risk',
    owner: 'مریم نوری',
    dealId: 5,
  },
  {
    id: 203,
    title: 'قرارداد سالانه شرکت فی',
    company: 'شرکت فی',
    contact: 'محمدرضا سلیمانی',
    stage: 'drafting',
    value: 890000000,
    startDate: '—',
    endDate: '—',
    daysRemaining: null,
    lastActivity: '۱ روز پیش',
    status: 'draft',
    owner: 'علی رضایی',
    dealId: 10,
  },
  {
    id: 204,
    title: 'قرارداد مشاوره گاما',
    company: 'شرکت گاما',
    contact: 'رضا کریمی',
    stage: 'legal_review',
    value: 320000000,
    startDate: '—',
    endDate: '—',
    daysRemaining: null,
    lastActivity: 'دیروز',
    status: 'reviewing',
    owner: 'مریم نوری',
    dealId: 3,
  },
  {
    id: 205,
    title: 'قرارداد اتوماسیون تتا',
    company: 'شرکت تتا',
    contact: 'امیر رستمی',
    stage: 'renewal',
    value: 520000000,
    startDate: '۱۴۰۴/۰۷/۰۱',
    endDate: '۱۴۰۵/۰۶/۳۰',
    daysRemaining: 10,
    lastActivity: '۵ روز پیش',
    status: 'needs_renewal',
    owner: 'علی رضایی',
    dealId: 8,
  },
  {
    id: 206,
    title: 'قرارداد قدیمی شرکت زتا',
    company: 'شرکت زتا',
    contact: 'حسن عباسی',
    stage: 'expired',
    value: 150000000,
    startDate: '۱۴۰۳/۰۷/۰۱',
    endDate: '۱۴۰۴/۰۶/۳۰',
    daysRemaining: -30,
    lastActivity: '۳۰ روز پیش',
    status: 'expired',
    owner: 'علی رضایی',
    dealId: 6,
  },
];

// Smart gate questions for follow-up transitions
export const followUpGates = {
  'new→initial_call': {
    title: 'ثبت تماس اولیه',
    description: 'برای انتقال به «تماس اولیه» تایید کنید:',
    questions: [
      { id: 'q1', text: 'آیا با مخاطب صحبت کرده‌اید؟' },
      { id: 'q2', text: 'آیا اطلاعات تماس تایید شده؟' },
    ],
  },
  'initial_call→followup_1': {
    title: 'شروع پیگیری',
    description: 'برای شروع پیگیری اول:',
    questions: [
      { id: 'q1', text: 'آیا علاقه‌مندی مشتری تایید شده؟' },
      { id: 'q2', text: 'آیا تاریخ پیگیری بعدی مشخص شده؟' },
    ],
  },
  'followup_1→followup_2': {
    title: 'پیگیری دوم',
    description: 'برای پیگیری دوم:',
    questions: [
      { id: 'q1', text: 'آیا پاسخی از مشتری دریافت شده؟' },
      { id: 'q2', text: 'آیا اقدام مشتری مشخص شده؟' },
    ],
  },
  'followup_2→followup_3': {
    title: 'پیگیری سوم (آخرین تلاش)',
    description: 'برای آخرین پیگیری:',
    questions: [
      { id: 'q1', text: 'آیا ۲ پیگیری قبلی ثبت شده؟' },
      { id: 'q2', text: 'آیا پیشنهاد جدیدی ارائه شده؟' },
    ],
  },
  'followup_3→successful': {
    title: 'تبدیل به موفق 🎉',
    description: 'آیا معامله با موفقیت پیش رفته؟',
    questions: [
      { id: 'q1', text: 'آیا مشتری موافقت کرده؟' },
      { id: 'q2', text: 'آیا قرارداد در حال تنظیم است؟' },
    ],
  },
};

// Smart gate questions for contract transitions
export const contractGates = {
  'drafting→legal_review': {
    title: 'ارسال به بررسی حقوقی',
    description: 'برای ارسال قرارداد به واحد حقوقی:',
    questions: [
      { id: 'q1', text: 'آیا شرایط کلی توافق شده؟' },
      { id: 'q2', text: 'آیا مبلغ و مدت قرارداد مشخص است؟' },
    ],
  },
  'legal_review→awaiting_signature': {
    title: 'آماده امضا',
    description: 'برای ارسال قرارداد جهت امضا:',
    questions: [
      { id: 'q1', text: 'آیا بررسی حقوقی بدون مشکل بوده؟' },
      { id: 'q2', text: 'آیا تمام بندها تایید شده؟' },
    ],
  },
  'awaiting_signature→active': {
    title: 'فعال‌سازی قرارداد 🎉',
    description: 'آیا قرارداد امضا شده و آماده فعال‌سازی است؟',
    questions: [
      { id: 'q1', text: 'آیا امضا دریافت شده؟' },
      { id: 'q2', text: 'آیا اولین پرداخت ثبت شده؟' },
    ],
  },
  'active→renewal': {
    title: 'شروع فرآیند تمدید',
    description: 'قرارداد نیاز به تمدید دارد:',
    questions: [
      { id: 'q1', text: 'آیا کمتر از ۳۰ روز به اتمام مانده؟' },
      { id: 'q2', text: 'آیا با مشتری درباره تمدید صحبت شده؟' },
    ],
  },
};

export const formatCurrency = (value) => {
  return new Intl.NumberFormat('fa-IR').format(value) + ' تومان';
};

export const getHealthColor = (health) => {
  if (health >= 70) return 'text-success';
  if (health >= 40) return 'text-warning';
  return 'text-danger';
};

export const getHealthBg = (health) => {
  if (health >= 70) return 'bg-success/10 border-success/20';
  if (health >= 40) return 'bg-warning/10 border-warning/20';
  return 'bg-danger/10 border-danger/20';
};

// Smart gate questions for each stage transition
// Each transition has questions that must be answered 'yes' to advance
export const smartGates = {
  'lead→qualified': {
    title: 'تایید صلاحیت سرنخ',
    description: 'برای انتقال به مرحله «تایید شده»، لطفاً موارد زیر را تایید کنید:',
    questions: [
      { id: 'q1', text: 'آیا با مخاطب صحبت کرده‌اید؟', autoCheck: null },
      { id: 'q2', text: 'آیا اطلاعات تماس تکمیل است؟', autoCheck: 'contactComplete' },
      { id: 'q3', text: 'آیا نیاز اولیه مشتری مشخص شده؟', autoCheck: null },
    ],
  },
  'qualified→discovery': {
    title: 'شروع کشف نیاز',
    description: 'برای ورود به مرحله «کشف نیاز»:',
    questions: [
      { id: 'q1', text: 'آیا جلسه معرفی برگزار شده؟', autoCheck: null },
      { id: 'q2', text: 'آیا علاقه‌مندی مشتری تایید شده؟', autoCheck: null },
    ],
  },
  'discovery→proposal': {
    title: 'ارسال پیشنهاد',
    description: 'برای ارسال پیشنهاد:',
    questions: [
      { id: 'q1', text: 'آیا نیازهای مشتری کاملاً شناسایی شده؟', autoCheck: null },
      { id: 'q2', text: 'آیا بودجه مشتری تایید شده؟', autoCheck: null },
      { id: 'q3', text: 'آیا حداقل ۳ فعالیت ثبت شده؟', autoCheck: 'minActivities' },
    ],
  },
  'proposal→negotiation': {
    title: 'ورود به مذاکره',
    description: 'برای شروع مذاکره:',
    questions: [
      { id: 'q1', text: 'آیا پیشنهاد ارسال شده؟', autoCheck: null },
      { id: 'q2', text: 'آیا بازخورد مشتری دریافت شده؟', autoCheck: null },
    ],
  },
  'negotiation→won': {
    title: 'بستن معامله 🎉',
    description: 'تبریک! برای نهایی کردن:',
    questions: [
      { id: 'q1', text: 'آیا شرایط نهایی توافق شده؟', autoCheck: null },
      { id: 'q2', text: 'آیا قرارداد امضا شده؟', autoCheck: null },
    ],
  },
};

// Next stage probability mapping
export const stageProbabilities = {
  lead: 10,
  qualified: 25,
  discovery: 40,
  proposal: 55,
  negotiation: 70,
  won: 100,
};
