export const stages = [
  { id: 'lead', label: 'سرنخ', color: '#6366f1', count: 3 },
  { id: 'qualified', label: 'تایید شده', color: '#3b82f6', count: 2 },
  { id: 'discovery', label: 'کشف نیاز', color: '#06b6d4', count: 2 },
  { id: 'proposal', label: 'پیشنهاد', color: '#f59e0b', count: 2 },
  { id: 'negotiation', label: 'مذاکره', color: '#f97316', count: 2 },
  { id: 'won', label: 'برنده', color: '#22c55e', count: 1 },
];

export const deals = [
  {
    id: 1,
    title: 'قرارداد CRM شرکت آلفا',
    company: 'شرکت آلفا',
    contact: 'علی محمدی',
    value: 450000000,
    stage: 'negotiation',
    health: 78,
    probability: 70,
    daysInStage: 5,
    lastActivity: '۲ روز پیش',
    lastActivityType: 'تماس تلفنی',
    nextAction: 'ارسال پیشنهاد نهایی',
    createdAt: '۱۴۰۵/۰۶/۰۱',
    owner: 'علی رضایی',
    tags: ['بزرگ', 'SaaS', 'تهران'],
  },
  {
    id: 2,
    title: 'پروژه دیجیتال مارکتینگ بتا',
    company: 'شرکت بتا',
    contact: 'سارا احمدی',
    value: 180000000,
    stage: 'proposal',
    health: 45,
    probability: 50,
    daysInStage: 12,
    lastActivity: '۸ روز پیش',
    lastActivityType: 'ایمیل',
    nextAction: 'پیگیری پیشنهاد ارسال شده',
    createdAt: '۱۴۰۵/۰۵/۲۰',
    owner: 'علی رضایی',
    tags: ['متوسط', 'مارکتینگ'],
  },
  {
    id: 3,
    title: 'فروش لایسنس نرم‌افزار گاما',
    company: 'شرکت گاما',
    contact: 'رضا کریمی',
    value: 320000000,
    stage: 'discovery',
    health: 82,
    probability: 40,
    daysInStage: 3,
    lastActivity: 'دیروز',
    lastActivityType: 'جلسه آنلاین',
    nextAction: 'ارسال سوالات کشف نیاز',
    createdAt: '۱۴۰۵/۰۶/۱۰',
    owner: 'مریم نوری',
    tags: ['بزرگ', 'نرم‌افزار'],
  },
  {
    id: 4,
    title: 'مشاوره ERP شرکت دلتا',
    company: 'شرکت دلتا',
    contact: 'مهدی حسینی',
    value: 95000000,
    stage: 'qualified',
    health: 60,
    probability: 30,
    daysInStage: 7,
    lastActivity: '۵ روز پیش',
    lastActivityType: 'فرم وب',
    nextAction: 'تماس برای جلسه معرفی',
    createdAt: '۱۴۰۵/۰۶/۰۵',
    owner: 'علی رضایی',
    tags: ['کوچک', 'ERP'],
  },
  {
    id: 5,
    title: 'قرارداد پشتیبانی شرکت اپسیلون',
    company: 'شرکت اپسیلون',
    contact: 'نیلوفر شریفی',
    value: 670000000,
    stage: 'negotiation',
    health: 35,
    probability: 60,
    daysInStage: 18,
    lastActivity: '۱۲ روز پیش',
    lastActivityType: 'ایمیل',
    nextAction: 'تماس فوری - معامله در خطر',
    createdAt: '۱۴۰۵/۰۴/۱۵',
    owner: 'مریم نوری',
    tags: ['بزرگ', 'پشتیبانی', 'در خطر'],
  },
  {
    id: 6,
    title: 'سیستم حسابداری شرکت زتا',
    company: 'شرکت زتا',
    contact: 'حسن عباسی',
    value: 150000000,
    stage: 'lead',
    health: 90,
    probability: 10,
    daysInStage: 1,
    lastActivity: 'امروز',
    lastActivityType: 'فرم وب',
    nextAction: 'بررسی صلاحیت سرنخ',
    createdAt: '۱۴۰۵/۰۶/۱۹',
    owner: 'علی رضایی',
    tags: ['کوچک', 'حسابداری'],
  },
  {
    id: 7,
    title: 'پلتفرم آموزش آنلاین اتا',
    company: 'شرکت اتا',
    contact: 'زهرا کاظمی',
    value: 280000000,
    stage: 'proposal',
    health: 72,
    probability: 55,
    daysInStage: 6,
    lastActivity: '۳ روز پیش',
    lastActivityType: 'جلسه حضوری',
    nextAction: 'ارسال نمونه پروژه قبلی',
    createdAt: '۱۴۰۵/۰۵/۲۸',
    owner: 'مریم نوری',
    tags: ['متوسط', 'آموزش'],
  },
  {
    id: 8,
    title: 'اتوماسیون بازاریابی شرکت تتا',
    company: 'شرکت تتا',
    contact: 'امیر رستمی',
    value: 520000000,
    stage: 'discovery',
    health: 88,
    probability: 35,
    daysInStage: 2,
    lastActivity: 'دیروز',
    lastActivityType: 'تلفن',
    nextAction: 'برنامه‌ریزی جلسه دوم',
    createdAt: '۱۴۰۵/۰۶/۱۲',
    owner: 'علی رضایی',
    tags: ['بزرگ', 'اتوماسیون'],
  },
  {
    id: 9,
    title: 'فروش سخت‌افزار شرکت یوتا',
    company: 'شرکت یوتا',
    contact: 'پریسا مهدوی',
    value: 85000000,
    stage: 'lead',
    health: 95,
    probability: 5,
    daysInStage: 0,
    lastActivity: 'امروز',
    lastActivityType: 'لینکدین',
    nextAction: 'ارسال پیام معرفی',
    createdAt: '۱۴۰۵/۰۶/۱۹',
    owner: 'مریم نوری',
    tags: ['کوچک', 'سخت‌افزار'],
  },
  {
    id: 10,
    title: 'قرارداد سالانه شرکت فی',
    company: 'شرکت فی',
    contact: 'محمدرضا سلیمانی',
    value: 890000000,
    stage: 'won',
    health: 100,
    probability: 100,
    daysInStage: 0,
    lastActivity: '۱ روز پیش',
    lastActivityType: 'امضای قرارداد',
    nextAction: 'شروع پروژه آنبوردینگ',
    createdAt: '۱۴۰۵/۰۳/۰۱',
    owner: 'علی رضایی',
    tags: ['بزرگ', 'سالانه', 'برنده شده'],
  },
  {
    id: 11,
    title: 'مشاوره دیجیتال شرکت کاپا',
    company: 'شرکت کاپا',
    contact: 'الهام جعفری',
    value: 120000000,
    stage: 'lead',
    health: 85,
    probability: 8,
    daysInStage: 2,
    lastActivity: '۲ روز پیش',
    lastActivityType: 'فرم وب',
    nextAction: 'بررسی و تایید صلاحیت',
    createdAt: '۱۴۰۵/۰۶/۱۷',
    owner: 'مریم نوری',
    tags: ['متوسط', 'مشاوره'],
  },
  {
    id: 12,
    title: 'سیستم مدیریت محتوا شرکت لاندا',
    company: 'شرکت لاندا',
    contact: 'بهنام امیری',
    value: 230000000,
    stage: 'qualified',
    health: 55,
    probability: 25,
    daysInStage: 9,
    lastActivity: '۷ روز پیش',
    lastActivityType: 'ایمیل',
    nextAction: 'ارسال دعوتنامه جلسه',
    createdAt: '۱۴۰۵/۰۵/۳۰',
    owner: 'علی رضایی',
    tags: ['متوسط', 'CMS'],
  },
];

export const contacts = [
  { id: 1, name: 'علی محمدی', company: 'شرکت آلفا', phone: '۰۹۱۲۱۲۳۴۵۶۷', email: 'ali@alpha.com', role: 'مدیر فروش', lastContact: '۲ روز پیش', dealCount: 1, avatar: 'ع' },
  { id: 2, name: 'سارا احمدی', company: 'شرکت بتا', phone: '۰۹۱۹۸۷۶۵۴۳۲', email: 'sara@beta.com', role: 'مدیر پروژه', lastContact: '۸ روز پیش', dealCount: 1, avatar: 'س' },
  { id: 3, name: 'رضا کریمی', company: 'شرکت گاما', phone: '۰۹۱۱۱۱۱۱۱۱۱', email: 'reza@gamma.com', role: 'مدیر عامل', lastContact: 'دیروز', dealCount: 1, avatar: 'ر' },
  { id: 4, name: 'مهدی حسینی', company: 'شرکت دلتا', phone: '۰۹۱۲۲۲۲۲۲۲۲', email: 'mehdi@delta.com', role: 'مدیر IT', lastContact: '۵ روز پیش', dealCount: 1, avatar: 'م' },
  { id: 5, name: 'نیلوفر شریفی', company: 'شرکت اپسیلون', phone: '۰۹۱۹۳۳۳۳۳۳۳', email: 'niloufar@epsilon.com', role: 'مدیر خرید', lastContact: '۱۲ روز پیش', dealCount: 1, avatar: 'ن' },
  { id: 6, name: 'حسن عباسی', company: 'شرکت زتا', phone: '۰۹۱۲۴۴۴۴۴۴۴۴', email: 'hasan@zeta.com', role: 'حسابدار', lastContact: 'امروز', dealCount: 1, avatar: 'ح' },
  { id: 7, name: 'زهرا کاظمی', company: 'شرکت اتا', phone: '۰۹۱۹۵۵۵۵۵۵۵', email: 'zahra@eta.com', role: 'مدیر آموزش', lastContact: '۳ روز پیش', dealCount: 1, avatar: 'ز' },
  { id: 8, name: 'امیر رستمی', company: 'شرکت تتا', phone: '۰۹۱۲۶۶۶۶۶۶۶', email: 'amir@theta.com', role: 'مدیر بازاریابی', lastContact: 'دیروز', dealCount: 1, avatar: 'ا' },
];

export const activities = [
  { id: 1, dealId: 1, type: 'call', title: 'تماس تلفنی', description: 'پیگیری شرایط قرارداد و بحث درباره قیمت', date: '۱۴۰۵/۰۶/۱۷', time: '۱۴:۳۰', icon: '📞' },
  { id: 2, dealId: 1, type: 'meeting', title: 'جلسه آنلاین', description: 'ارائه نهایی پیشنهاد به تیم خرید آلفا', date: '۱۴۰۵/۰۶/۱۵', time: '۱۰:۰۰', icon: '📹' },
  { id: 3, dealId: 1, type: 'email', title: 'ایمیل', description: 'ارسال شرایط تفصیلی قرارداد', date: '۱۴۰۵/۰۶/۱۴', time: '۱۱:۲۰', icon: '📧' },
  { id: 4, dealId: 1, type: 'task', title: 'تسک', description: 'تهیه پروپوزال نهایی', date: '۱۴۰۵/۰۶/۱۲', time: '۰۹:۰۰', icon: '✅' },
  { id: 5, dealId: 5, type: 'call', title: 'تماس تلفنی', description: 'بازخورد منفی درباره قیمت - نیاز به تخفیف', date: '۱۴۰۵/۰۶/۰۷', time: '۱۶:۰۰', icon: '📞' },
  { id: 6, dealId: 5, type: 'email', title: 'ایمیل', description: 'ارسال فاکتور اصلاح شده', date: '۱۴۰۵/۰۶/۰۵', time: '۱۰:۳۰', icon: '📧' },
  { id: 7, dealId: 5, type: 'meeting', title: 'جلسه حضوری', description: 'مذاکره حضوری در دفتر شرکت اپسیلون', date: '۱۴۰۵/۰۶/۰۱', time: '۱۴:۰۰', icon: '🤝' },
  { id: 8, dealId: 10, type: 'task', title: 'تسک', description: 'امضای نهایی قرارداد و شروع آنبوردینگ', date: '۱۴۰۵/۰۶/۱۸', time: '۱۱:۰۰', icon: '✅' },
  { id: 9, dealId: 3, type: 'meeting', title: 'جلسه آنلاین', description: 'کشف نیازهای اصلی شرکت گاما', date: '۱۴۰۵/۰۶/۱۸', time: '۰۹:۳۰', icon: '📹' },
  { id: 10, dealId: 8, type: 'call', title: 'تماس تلفنی', description: 'معرفی اولیه پلتفرم اتوماسیون', date: '۱۴۰۵/۰۶/۱۸', time: '۱۵:۰۰', icon: '📞' },
];

export const aiInsights = [
  { id: 1, type: 'danger', title: 'معامله در خطر', message: 'قرارداد پشتیبانی اپسیلون ۱۸ روز بدون فعالیت است. احتمال از دست رفتن: ۶۵٪', action: 'تماس فوری', dealId: 5 },
  { id: 2, type: 'warning', title: 'پیگیری عقب‌افتاده', message: 'پیشنهاد شرکت بتا ۱۲ روز ارسال شده و پاسخی دریافت نشده', action: 'ارسال یادآوری', dealId: 2 },
  { id: 3, type: 'success', title: 'معامله با احتمال بالا', message: 'قرارداد آلفا در مرحله مذاکره با احتمال ۷۰٪ — آماده بستن', action: 'پیگیری نهایی', dealId: 1 },
  { id: 4, type: 'info', title: 'پیشنهاد هوشمند', message: 'بر اساس الگوهای تاریخی، معاملات مشابه با شرکت‌های بزرگ بعد از ۳ جلسه بسته می‌شوند', action: 'مشاهده', dealId: 3 },
  { id: 5, type: 'info', title: 'تحلیل فصلی', message: 'نرخ تبدیل فروش در این فصل نسبت به فصل قبل ۱۵٪ بهبود داشته', action: 'مشاهده گزارش', dealId: null },
];

export const formatCurrency = (value) => {
  return new Intl.NumberFormat('fa-IR').format(value) + ' تومان';
};

export const getHealthColor = (health) => {
  if (health >= 70) return 'text-success';
  if (health >= 40) return 'text-warning';
  return 'text-danger';
};

export const getHealthBg = (health) => {
  if (health >= 70) return 'bg-success/10 border-success/20';
  if (health >= 40) return 'bg-warning/10 border-warning/20';
  return 'bg-danger/10 border-danger/20';
};
